### PR TITLE
my mastake it was 107

### PR DESCRIPTION
**Pull request by caspervanneck**

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
I just realised how outdated that is. Look on my wiki http://pe.thediamondyt.tk/wiki/protocol/

**Comment by caspervanneck** [comment]
@TheDiamondYT1 yap

**Comment by caspervanneck** [comment]
@TheDiamondYT1

**Comment by caspervanneck** [comment]
aaa conflict now i mustmake new one

**Comment by TheDiamondYT1** [comment]
No dont please login doesnt even work yet just leave it on 1.0.6

**Comment by caspervanneck** [comment]
yes @TheDiamondYT1

**Pull request closed without merging**
