### PR TITLE
Make Basic Structure

### PR DESCRIPTION
**Pull request by Magicode1**
Is this what you wanted done? I made the POMs as placeholders, because I don't know if this is what you meant :)

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
Move the api and server folders to the root of the repo and delete the Dragonet folder. 

I will leave this open as i might be able to go on my PC in about an hour and actually add some code. Maven modules are a d*ck to set up

**Comment by TheDiamondYT1** [comment]
I really should make the initial commit actually, i didnt think about this lol

**Comment by Magicode1** [comment]
Sounds good. I will wait until the init comes :+1:

**Comment by TheDiamondYT1** [comment]
@Magicode1 Oh and i will add you to this repo afterwards if you arent already

**Pull request closed without merging**
