### PR TITLE
Fixed building

### PR DESCRIPTION
**Pull request by DaMatrix**

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
We need to include the Dragonet-server dependency as there are Dragonet imports in Glowstone

**Comment by DaMatrix** [comment]
ok so dragonet-server needs to be packaged inside glowstone*.jar?

**Comment by TheDiamondYT1** [comment]
No...

**Comment by TheDiamondYT1** [comment]
Actually idk i think so but they depend on each other. Im deleting this repo now, i like Voxelwind

**Comment by TheDiamondYT1** [comment]
So say your goodbyes

**Pull request closed without merging**
